name = "Cobblemon Modpack [Fabric]"
author = "Cobblemon"
version = "1.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97d8aecd4eaa1fdfd8416068582c92e40557dceee840c10b27f73511e91cdd56"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
